version: '3'
services:
  api:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWD=123456
      - DB_NAME=shopper
      - DB_PORT=3306
      - API_PORT=8080
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    ports:
      - '80:80'
    depends_on:
      - api
  db:
    image: postgres:15.3
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=shopper

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '${PWD}/dbdata'
