version: '3'
services:
  api:
    # image: victorhdchagas/shopper-api
    # platform: linux/amd64,linux/arm64
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWD=mysecretpassword
      - DB_NAME=shopper
      - DB_PORT=5432
      - API_PORT=8080
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    command: ['node', 'dist/main']
  frontend:
    # image: victorhdchagas/shopper-front
    # platform: linux/amd64,linux/arm64
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    ports:
      - '80:80'
    depends_on:
      - api

  db:
    # image: victorhdchagas/shopper-db
    # platform: linux/amd64,linux/arm64
    build:
      context: ./db
      dockerfile: docker/Dockerfile
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: shopper
    ports:
      - '5432:5432'
    volumes:
      - data_sql:/var/lib/postgresql/data # Persistent data storage

volumes:
  data_sql:
